### ISSUE TITLE
Elements

### ISSUE THREAD

**Issue by matt439miller** [jakesower/rpg-2024#12]
You seem to be into the elements, or at least the damage types. But it does suggest we may just want to say fuck the ideals, and go with elements as our atoms. Then we go apeshit with the number of elements, and get into all the dnd damage types (radiant, necrotic). Hmm. Maybe start with damage types, then classify all the ideal combos as a damage type.

**Comment by jakesower** [comment]
You can never get "control mind" from elements. Also, scrying? Necromancy? Summoning? These are things that don't work with elements unless you expand the number of elements into something incoherent.

I'm mostly into trying to vary attack spells. I think that most spells a caster uses in combat are attack spells. (Then buffs, then debuffs, then everything else.) I don't want a "Harm Other" spell that covers this. Also, fireballs and lightning bolts should feel different, even if the point of them is the same. Elements are convenient groupings for this sort of thought, but that's it.

**Comment by matt439miller** [comment]
Ok, fuck that then. May still want to stat damage types with colors (radiant, necrotic, burning, freezing, acid, poison, etc).
