### ISSUE TITLE
Wargame

### ISSUE THREAD

**Issue by matt439miller** [jakesower/rpg-2024#2]
Intend to think of a war game as the skeleton of any tactical rpg (ie any where you count squares hexes or measure distance). Past that comes the rules governing the conflicts ie how hits translate into losses. Ie, base mechanic and HP. Which ramifies quickly into all the different attack types available. In a war game, that would be by unit, but in a skirmish game, that's by class or class level, or gear owned or equipped. Somewhere in there are conditions/states that affect the base mechanic (ie flanking or advantage).

**Comment by jakesower** [comment]
Yeah. I think skirmish game is the way to go. I have no interest in a wargame as you describe it.
