### ISSUE TITLE
Bursts

### ISSUE THREAD

**Issue by matt439miller** [jakesower/rpg-2024#3]
Within limited info, I'm assuming that bursts are bursts of activity and hence actions per round. Tying it to an attribute makes me blood run a bit cold. I recall that from Deadlands--you drew as many poker cards as you had wit, and then used those cards to count initiative. Biscuit built a character that drew like 7...and it was terrible to play. Like everyone else taking one action and him taking seven. Worst ratio you'll have is 5:2, so not as bad. But it will mean abilities to increase wit will need to be verboten. Pathfinder running with a standard 3 has been nice, but the dnd 5e move plus attack plus bonus plus interaction has been clumsy.

**Comment by jakesower** [comment]
I need to rename these and describe them better.
